###Local: Get all towns
GET http://localhost:8080/towns

###Local: Get single town
GET http://localhost:8080/towns/single/646c43bbc1d9c797c97697f5

###Local: Insert town
POST http://localhost:8080/towns/insert HTTP/1.1
content-type: application/json

{
"town":"Pallet Town",
"area_id":"d7b09438ac1283c8255d09a1",
"badge":"none",
"enemies":"Gary",
"items":"town map",
"leader":"Prof. Oaks",
"mission":"Get first pokemon and go to the next city",
"gym":"No"
}

###Local: Insert Pokemon
POST http://localhost:8080/towns/insertpokemons HTTP/1.1
content-type: application/json

{
"area_id":"d7b09438ac1283c8255d09a1",
"Pokemons":"Pidgey, Caterpie, Ratata"
}

###Local: Update town
PUT http://localhost:8080/towns/update/6476f953f5944190ad7178b0 HTTP/1.1
content-type: application/json

{
"town":"Pallet Town",
"area_id":"d7b09438ac1283c8255d09a1",
"badge":"none",
"enemies":"Gary",
"items":"town map",
"leader":"Prof. Oaks",
"mission":"Get first pokemon and go to the next city",
"gym":"No"
}

###Update: Pokemons
PUT http://localhost:8080/towns/update/647cff9e9cd54e26505edd9f HTTP/1.1
content-type: application/json

{
"area_id":"d7b09438ac1283c8255d09a1",
"Pokemons":"Pidgey, Caterpie, Ratata"
}

###Local: Delete town
DELETE http://localhost:8080/towns/delete/6476f953f5944190ad7178b0 HTTP/1.1


###Local: Delete pokemons
DELETE http://localhost:8080/towns/delete/647cff9e9cd54e26505edd9f HTTP/1.1




###Live: Get all towns
GET https://pokemon-api-tztm.onrender.com/towns

###Live: Get single town
GET https://pokemon-api-tztm.onrender.com/towns/single/646c43bbc1d9c797c97697f5

###Live: Insert town
POST https://pokemon-api-tztm.onrender.com/towns/insert HTTP/1.1
content-type: application/json

{
"town":"Pallet Town",
"area_id":"d7b09438ac1283c8255d09a1",
"badge":"none",
"enemies":"Gary",
"items":"town map",
"leader":"Prof. Oaks",
"mission":"Get first pokemon and go to the next city",
"gym":"No"
}

###Live: Insert Pokemon
POST https://pokemon-api-tztm.onrender.com/insertpokemons HTTP/1.1
content-type: application/json

{
"area_id":"d7b09438ac1283c8255d09a1",
"Pokemons":"Pidgey, Caterpie, Ratata"
}

###Live: Update contact
PUT https://pokemon-api-tztm.onrender.com/towns/update/6476f953f5944190ad7178b0 HTTP/1.1
content-type: application/json

{
"town":"Pallet Town",
"area_id":"d7b09438ac1283c8255d09a1",
"badge":"none",
"enemies":"Gary",
"items":"town map",
"leader":"Prof. Oaks",
"mission":"Get first pokemon and go to the next city",
"gym":"No"
}

###Live: Update Pokemons
PUT https://pokemon-api-tztm.onrender.com/towns/updatepokemons/647cff9e9cd54e26505edd9f HTTP/1.1
content-type: application/json

{
"area_id":"d7b09438ac1283c8255d09a1",
"Pokemons":"Pidgey, Caterpie, Ratata"
}


###Live: Delete town
DELETE https://pokemon-api-tztm.onrender.com/towns/delete/6476f953f5944190ad7178b0 HTTP/1.1

###Live: Delete pokemons
DELETE https://pokemon-api-tztm.onrender.com/pokemons/delete/647cff9e9cd54e26505edd9f HTTP/1.1